exports.assetsData = [
  {
    id: 1,
    name: "asset-1",
    scope_1_emissions: 90,
    scope_2_emissions: 10,
    scope_3_emissions: 30,
    activities_affecting_biodiversity: false,
  },
  {
    id: 2,
    name: "asset-2",
    scope_1_emissions: 20,
    scope_2_emissions: 50,
    scope_3_emissions: 45,
    activities_affecting_biodiversity: true,
  },
  {
    id: 3,
    name: "asset-3",
    scope_1_emissions: 70,
    scope_2_emissions: 100,
    scope_3_emissions: 40,
    activities_affecting_biodiversity: true,
  },
  {
    id: 4,
    name: "asset-4",
    scope_1_emissions: 40,
    scope_2_emissions: 30,
    scope_3_emissions: 10,
    activities_affecting_biodiversity: false,
  },
  {
    id: 5,
    name: "asset-5",
    scope_1_emissions: 50,
    scope_2_emissions: 70,
    scope_3_emissions: 60,
    activities_affecting_biodiversity: false,
  },
  {
    id: 6,
    name: "asset-6",
    scope_1_emissions: 60,
    scope_2_emissions: 90,
    scope_3_emissions: 60,
    activities_affecting_biodiversity: false,
  },
  {
    id: 7,
    name: "asset-7",
    scope_1_emissions: 30,
    scope_2_emissions: 35,
    scope_3_emissions: 15,
    activities_affecting_biodiversity: true,
  },
  {
    id: 8,
    name: "asset-8",
    scope_1_emissions: 80,
    scope_2_emissions: 10,
    scope_3_emissions: 25,
    activities_affecting_biodiversity: false,
  },
  {
    id: 9,
    name: "asset-9",
    scope_1_emissions: 10,
    scope_2_emissions: 60,
    scope_3_emissions: 30,
  },
  {
    id: 10,
    name: "asset-10",
    scope_1_emissions: 100,
    scope_2_emissions: 25,
    scope_3_emissions: 55,
    activities_affecting_biodiversity: null,
  },
];
